apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistapp
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      containers:
      - name: todolist-container
        image: mx-queretaro-1.ocir.io/axxjocxrvfar/todolistapp-springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: TNS_ADMIN
          value: /app/src/main/resources/wallet
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: LoadBalancer
  selector:
    app: todolistapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
